name: Publish AIRAC MBTiles

on:
  workflow_dispatch:
    inputs:
      airac_cycle:
        description: "AIRAC cycle (e.g. 2503 or 'latest')"
        required: true
      bbox:
        description: "Bounding box coordinates (min_lon min_lat max_lon max_lat)"
        required: true
        default: "5.9 45.8 10.5 47.8"
      zoom:
        description: "Zoom range (min_zoom max_zoom)"
        required: true
        default: "7 12"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt tqdm aiohttp mercantile

      - name: Prepare bbox and zoom
        id: params
        run: |
          # Split bbox and zoom strings into shell arrays
          BBOX=(${{ github.event.inputs.bbox }})
          ZOOM=(${{ github.event.inputs.zoom }})
          echo "min_lon=${BBOX[0]}" >> $GITHUB_OUTPUT
          echo "min_lat=${BBOX[1]}" >> $GITHUB_OUTPUT
          echo "max_lon=${BBOX[2]}" >> $GITHUB_OUTPUT
          echo "max_lat=${BBOX[3]}" >> $GITHUB_OUTPUT
          echo "min_zoom=${ZOOM[0]}" >> $GITHUB_OUTPUT
          echo "max_zoom=${ZOOM[1]}" >> $GITHUB_OUTPUT

      - name: Generate MBTiles
        run: |
          mkdir -p mbtiles
          echo "🔹 Generating AIRAC=${{ github.event.inputs.airac_cycle }} bbox=${{ github.event.inputs.bbox }} zoom=${{ github.event.inputs.zoom }}"
          python generate_mbtiles.py \
            --bbox ${{ steps.params.outputs.min_lon }} ${{ steps.params.outputs.min_lat }} ${{ steps.params.outputs.max_lon }} ${{ steps.params.outputs.max_lat }} \
            --zoom ${{ steps.params.outputs.min_zoom }} ${{ steps.params.outputs.max_zoom }} \
            --airac ${{ github.event.inputs.airac_cycle }}
          ls -lh mbtiles/

      - name: Get generated file name
        id: findfile
        run: |
          FILE=$(ls -t mbtiles/*.mbtiles | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "📦 Found MBTiles: $FILE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "AIRAC-${{ github.event.inputs.airac_cycle }}"
          name: "AIRAC ${{ github.event.inputs.airac_cycle }}"
          body: |
            Automated release for AIRAC cycle **${{ github.event.inputs.airac_cycle }}**  
            Bounding box: `${{ github.event.inputs.bbox }}`  
            Zoom range: `${{ github.event.inputs.zoom }}`
          files: ${{ steps.findfile.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update "latest" symlink and commit
        run: |
          cd mbtiles
          FILE=$(ls -t *.mbtiles | head -n 1)
          ln -sf "$FILE" latest
          cd ..
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add mbtiles/latest
          git commit -m "Update latest to $FILE" || echo "No changes to commit"
          git push
